export default  {
  'Andorra': '/icons/countries/ad.svg',
  'United Arab Emirates': '/icons/countries/ae.svg',
  'Afghanistan': '/icons/countries/af.svg',
  'Antigua and Barbuda': '/icons/countries/ag.svg',
  'Anguilla': '/icons/countries/ai.svg',
  'Albania': '/icons/countries/al.svg',
  'Armenia': '/icons/countries/am.svg',
  'Angola': '/icons/countries/ao.svg',
  'Antarctica': '/icons/countries/aq.svg',
  'Argentina': '/icons/countries/ar.svg',
  'American Samoa': '/icons/countries/as.svg',
  'Austria': '/icons/countries/at.svg',
  'Australia': '/icons/countries/au.svg',
  'Aruba': '/icons/countries/aw.svg',
  'Aland Islands': '/icons/countries/ax.svg',
  'Azerbaijan': '/icons/countries/az.svg',
  'Bosnia and Herzegovina': '/icons/countries/ba.svg',
  'Barbados': '/icons/countries/bb.svg',
  'Bangladesh': '/icons/countries/bd.svg',
  'Belgium': '/icons/countries/be.svg',
  'Burkina Faso': '/icons/countries/bf.svg',
  'Bulgaria': '/icons/countries/bg.svg',
  'Bahrain': '/icons/countries/bh.svg',
  'Burundi': '/icons/countries/bi.svg',
  'Benin': '/icons/countries/bj.svg',
  'Saint Barthélemy': '/icons/countries/bl.svg',
  'Bolivia': '/icons/countries/bm.svg',
  'Brunei': '/icons/countries/bn.svg',
  'Brazil': '/icons/countries/bo.svg',
  'Bonaire, Sint Eustatius and Saba': '/icons/countries/bq.svg',
  'Bahamas': '/icons/countries/bs.svg',
  'Bhutan': '/icons/countries/bt.svg',
  'Bouvet Island': '/icons/countries/bv.svg',
  'Botswana': '/icons/countries/bw.svg',
  'Belarus': '/icons/countries/by.svg',
  'Belize': '/icons/countries/bz.svg',
  
  'Canada': '/icons/countries/ca.svg',
  'Cocos (Keeling) Islands': '/icons/countries/cc.svg',
  'Democratic Republic of the Congo': '/icons/countries/cd.svg',
  'Central African Republic': '/icons/countries/cf.svg',
  'Republic of the Congo': '/icons/countries/cg.svg',
  'Switzerland': '/icons/countries/ch.svg',
  'Ivory Coast': '/icons/countries/ci.svg',
  'Cook Islands': '/icons/countries/ck.svg',
  'Chile': '/icons/countries/cl.svg',
  'Cameroon': '/icons/countries/cm.svg',
  'China': '/icons/countries/cn.svg',
  'Colombia': '/icons/countries/co.svg',
  'Costa Rica': '/icons/countries/cr.svg',
  'Cuba': '/icons/countries/cu.svg',
  'Cape Verde': '/icons/countries/cv.svg',
  'Curaçao': '/icons/countries/cw.svg',
  'Christmas Island': '/icons/countries/cx.svg',
  'Cyprus': '/icons/countries/cy.svg',
  'Czech Republic': '/icons/countries/cz.svg',
  'Germany': '/icons/countries/de.svg',
  'Djibouti': '/icons/countries/dj.svg',
  'Denmark': '/icons/countries/dk.svg',
  'Dominica': '/icons/countries/dm.svg',
  'Dominican Republic': '/icons/countries/do.svg',
  'Algeria': '/icons/countries/dz.svg',
  'Ecuador': '/icons/countries/ec.svg',
  'Estonia': '/icons/countries/ee.svg',
  'Egypt': '/icons/countries/eg.svg',
  'Western Sahara': '/icons/countries/eh.svg',
  'Eritrea': '/icons/countries/er.svg',
  'Spain': '/icons/countries/es.svg',
  'Ethiopia': '/icons/countries/et.svg',
  'European Union': '/icons/countries/eu.svg',
  'Finland': '/icons/countries/fi.svg',
  'Fiji': '/icons/countries/fj.svg',
  'Falkland Islands': '/icons/countries/fk.svg',
  'Micronesia': '/icons/countries/fm.svg',
  'Faroe Islands': '/icons/countries/fo.svg',
  'France': '/icons/countries/fr.svg',
  'Gabon': '/icons/countries/ga.svg',
  'England': '/icons/countries/gb-eng.svg',
  'Northern Ireland': '/icons/countries/gb-nir.svg',
  'Scotland': '/icons/countries/gb-sct.svg',
  'Wales': '/icons/countries/gb-wls.svg',
  'United Kingdom': '/icons/countries/gb.svg',
  'Grenada': '/icons/countries/gd.svg',
  'Georgia': '/icons/countries/ge.svg',
  'French Guiana': '/icons/countries/gf.svg',
  'Guernsey': '/icons/countries/gg.svg',
  'Ghana': '/icons/countries/gh.svg',
  'Gibraltar': '/icons/countries/gi.svg',
  'Greenland': '/icons/countries/gl.svg',
  'Gambia': '/icons/countries/gm.svg',
  'Guinea': '/icons/countries/gn.svg',
  'Guadeloupe': '/icons/countries/gp.svg',
  'Equatorial Guinea': '/icons/countries/gq.svg',
  'Greece': '/icons/countries/gr.svg',
  'South Georgia and the South Sandwich Islands': '/icons/countries/gs.svg',
  'Guatemala': '/icons/countries/gt.svg',
  'Guam': '/icons/countries/gu.svg',
  'Guinea-Bissau': '/icons/countries/gw.svg',
  'Guyana': '/icons/countries/gy.svg',
  'Hong Kong': '/icons/countries/hk.svg',
  'Heard Island and McDonald Islands': '/icons/countries/hm.svg',
  'Honduras': '/icons/countries/hn.svg',
  'Croatia': '/icons/countries/hr.svg',
  'Haiti': '/icons/countries/ht.svg',
  'Hungary': '/icons/countries/hu.svg',
  'Indonesia': '/icons/countries/id.svg',
  'Ireland': '/icons/countries/ie.svg',
  'Israel': '/icons/countries/il.svg',
  'Isle of Man': '/icons/countries/im.svg',
  'India': '/icons/countries/in.svg',
  'British Indian Ocean Territory': '/icons/countries/io.svg',
  'Iraq': '/icons/countries/iq.svg',
  'Iran': '/icons/countries/ir.svg',
  'Iceland': '/icons/countries/is.svg',
  'Italy': '/icons/countries/it.svg',
  'Jersey': '/icons/countries/je.svg',
  'Jamaica': '/icons/countries/jm.svg',
  'Jordan': '/icons/countries/jo.svg',
  'Japan': '/icons/countries/jp.svg',

  'Kenya': '/icons/countries/ke.svg',
  'Kyrgyzstan': '/icons/countries/kg.svg',
  'Cambodia': '/icons/countries/kh.svg',
  'Kiribati': '/icons/countries/ki.svg',
  'Comoros': '/icons/countries/km.svg',
  'Saint Kitts and Nevis': '/icons/countries/kn.svg',
  'North Korea': '/icons/countries/kp.svg',
  'South Korea': '/icons/countries/kr.svg',
  'Kuwait': '/icons/countries/kw.svg',
  'Cayman Islands': '/icons/countries/ky.svg',
  'Kazakhstan': '/icons/countries/kz.svg',
  'Laos': '/icons/countries/la.svg',
  'Lebanon': '/icons/countries/lb.svg',
  'Saint Lucia': '/icons/countries/lc.svg',
  'Liechtenstein': '/icons/countries/li.svg',
  'Sri Lanka': '/icons/countries/lk.svg',
  'Liberia': '/icons/countries/lr.svg',
  'Lesotho': '/icons/countries/ls.svg',
  'Lithuania': '/icons/countries/lt.svg',
  'Luxembourg': '/icons/countries/lu.svg',
  'Latvia': '/icons/countries/lv.svg',
  'Libya': '/icons/countries/ly.svg',
  'Morocco': '/icons/countries/ma.svg',
  'Monaco': '/icons/countries/mc.svg',
  'Moldova': '/icons/countries/md.svg',
  'Montenegro': '/icons/countries/me.svg',
  'Saint Martin': '/icons/countries/mf.svg',
  'Madagascar': '/icons/countries/mg.svg',
  'Marshall Islands': '/icons/countries/mh.svg',
  'North Macedonia': '/icons/countries/mk.svg',
  'Mali': '/icons/countries/ml.svg',
  'Myanmar (Burma)': '/icons/countries/mm.svg',
  'Mongolia': '/icons/countries/mn.svg',
  'Macau': '/icons/countries/mo.svg',
  'Northern Mariana Islands': '/icons/countries/mp.svg',
  'Martinique': '/icons/countries/mq.svg',
  'Mauritania': '/icons/countries/mr.svg',
  'Montserrat': '/icons/countries/ms.svg',
  'Malta': '/icons/countries/mt.svg',
  'Mauritius': '/icons/countries/mu.svg',
  'Maldives': '/icons/countries/mv.svg',
  'Malawi': '/icons/countries/mw.svg',
  'Mexico': '/icons/countries/mx.svg',
  'Malaysia': '/icons/countries/my.svg',
  'Mozambique': '/icons/countries/mz.svg',
  'Namibia': '/icons/countries/na.svg',
  'New Caledonia': '/icons/countries/nc.svg',
  'Niger': '/icons/countries/ne.svg',
  'Norfolk Island': '/icons/countries/nf.svg',
  'Nigeria': '/icons/countries/ng.svg',
  'Nicaragua': '/icons/countries/ni.svg',
  'Netherlands': '/icons/countries/nl.svg',
  'Norway': '/icons/countries/no.svg',
  'Nepal': '/icons/countries/np.svg',
  'Nauru': '/icons/countries/nr.svg',
  'Niue': '/icons/countries/nu.svg',
  'New Zealand': '/icons/countries/nz.svg',

  'Oman': '/icons/countries/om.svg',
  'Peru': '/icons/countries/pe.svg',
  'French Polynesia': '/icons/countries/pf.svg',
  'Papua New Guinea': '/icons/countries/pg.svg',
  'Philippines': '/icons/countries/ph.svg',
  'Pakistan': '/icons/countries/pk.svg',
  'Poland': '/icons/countries/pl.svg',
  'Saint Pierre and Miquelon': '/icons/countries/pm.svg',
  'Pitcairn Islands': '/icons/countries/pn.svg',
  'Puerto Rico': '/icons/countries/pr.svg',
  'Palestine': '/icons/countries/ps.svg',
  'Portugal': '/icons/countries/pt.svg',
  'Palau': '/icons/countries/pw.svg',
  'Paraguay': '/icons/countries/py.svg',
  'Qatar': '/icons/countries/qa.svg',
  'Réunion': '/icons/countries/re.svg',
  'Romania': '/icons/countries/ro.svg',
  'Serbia': '/icons/countries/rs.svg',
  'Russia': '/icons/countries/ru.svg',
  'Rwanda': '/icons/countries/rw.svg',
  'Saudi Arabia': '/icons/countries/sa.svg',
  'Solomon Islands': '/icons/countries/sb.svg',
  'Seychelles': '/icons/countries/sc.svg',
  'Sudan': '/icons/countries/sd.svg',
  'Sweden': '/icons/countries/se.svg',
  'Singapore': '/icons/countries/sg.svg',
  'Saint Helena': '/icons/countries/sh.svg',
  'Slovenia': '/icons/countries/si.svg',
  'Svalbard and Jan Mayen': '/icons/countries/sj.svg',
  'Slovakia': '/icons/countries/sk.svg',
  'Sierra Leone': '/icons/countries/sl.svg',
  'San Marino': '/icons/countries/sm.svg',
  'Senegal': '/icons/countries/sn.svg',
  'Somalia': '/icons/countries/so.svg',
  'Suriname': '/icons/countries/sr.svg',
  'South Sudan': '/icons/countries/ss.svg',
  'São Tomé and Príncipe': '/icons/countries/st.svg',
  'El Salvador': '/icons/countries/sv.svg',
  'Sint Maarten': '/icons/countries/sx.svg',
  'Syria': '/icons/countries/sy.svg',
  'Eswatini': '/icons/countries/sz.svg',
  'Turks and Caicos Islands': '/icons/countries/tc.svg',
  'Chad': '/icons/countries/td.svg',
  'French Southern Territories': '/icons/countries/tf.svg',
  'Togo': '/icons/countries/tg.svg',
  'Thailand': '/icons/countries/th.svg',
  'Tajikistan': '/icons/countries/tj.svg',
  'Tokelau': '/icons/countries/tk.svg',
  'Timor-Leste': '/icons/countries/tl.svg',
  'Turkmenistan': '/icons/countries/tm.svg',
  'Tunisia': '/icons/countries/tn.svg',
  'Tonga': '/icons/countries/to.svg',
  'Turkey': '/icons/countries/tr.svg',
  'Trinidad and Tobago': '/icons/countries/tt.svg',
  'Tuvalu': '/icons/countries/tv.svg',
  'Taiwan': '/icons/countries/tw.svg',
  'Tanzania': '/icons/countries/tz.svg',
  'Ukraine': '/icons/countries/ua.svg',
  'Uganda': '/icons/countries/ug.svg',
  'United States Minor Outlying Islands': '/icons/countries/um.svg',
  'United States': '/icons/countries/us.svg',
  'Uruguay': '/icons/countries/uy.svg',
  'Uzbekistan': '/icons/countries/uz.svg',
  'Vatican City': '/icons/countries/va.svg',
  'Saint Vincent and the Grenadines': '/icons/countries/vc.svg',
  'Venezuela': '/icons/countries/ve.svg',
  'British Virgin Islands': '/icons/countries/vg.svg',
  'U.S. Virgin Islands': '/icons/countries/vi.svg',
  'Vietnam': '/icons/countries/vn.svg',
  'Vanuatu': '/icons/countries/vu.svg',
  'Wallis and Futuna': '/icons/countries/wf.svg',
  'Samoa': '/icons/countries/ws.svg',
  'Kosovo': '/icons/countries/xk.svg',
  'Yemen': '/icons/countries/ye.svg',
  'Mayotte': '/icons/countries/yt.svg',
  'South Africa': '/icons/countries/za.svg',
  'Zambia': '/icons/countries/zm.svg',
  'Zimbabwe': '/icons/countries/zw.svg',
} as const;